export default function Head() {
  return (
    <Head>
      <title>SBH Shopping List</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
}
